# DCOS params:
zookeeper: "{{ groups['masters'] | join(':2181,') }}:2181"

# mesos-agent
resources_ports: "{{ over_resources_ports | default('10000-34000') }}"
system_user: "Administrator"

# specific for service run
mesos_workers:
  windows:
    service_name: "mesos-agent"
    attributes: "os:windows"
    homedir: "C:\\dcos"
    bindir: "C:\\dcos\\mesos-binaries"
    workdir: "C:\\dcos\\work"
    imagesdir: "C:\\dcos\\images"
    logdir: "C:\\dcos\\mesos-logs"
    executor: "C:\\dcos\\mesos-binaries\\mesos-agent.exe"
    executor_timeout: 10mins
    fetcher_timeout: 10mins

# specific for docker tls
dockertls:
  windows:
    service_name: "docker"
    image: "sergiimatusepam/dockertls-windows:latest"
    script: "C:\\docker-tls\\dockertls.ps1"
    volumes:
      engine_src: "C:\\ProgramData\\docker"
      engine_dst: "C:\\ProgramData\\docker"
      cli_src: "C:\\docker-tls\\client\\.docker"
      cli_dst: "C:\\Users\\ContainerAdministrator\\.docker"

# Packages location
bucket_name: "dcos-win.s3.amazonaws.com"
url_to_mesosbin: "http://{{ bucket_name }}/mesos-binaries.{{ dcos['version'] }}.zip"
